[relaychain]
chain = "rococo-local"
default_command = "./target/release/polkadot"
default_args = [ "-lparachain=debug" ]

    [[relaychain.nodes]]
    name = "alice"
    rpc_port = 9900
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "bob"
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "charlie"
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

    [[relaychain.nodes]]
    name = "dave"
    validator = true
    args = ["--trie-cache-size=0", "--disable-worker-version-check"]

[[parachains]]
id = 2000
addToGenesis = true
cumulus_based = true

    [[parachains.collators]]
    name = "test-para-collator01"
    rpc_port = 9920
    command = "./target/release/test-parachain"
    args = ["-ltest_pallet=info", "--", "--trie-cache-size=0", "--network-backend=libp2p"]

    [[parachains.collators]]
    name = "test-para-collator02"
    command = "./target/release/test-parachain"
    args = ["-ltest_pallet=info", "--", "--trie-cache-size=0", "--network-backend=libp2p"]
